version: '3'
services:
  web:
    build: .
    command: go run main.go
    ports:
      - "5000:8080"
    networks:
      - 12306-net

  redis:
    image: "redis:latest"
    networks:
      12306-net:

  mysql:
    image: "mysql:latest"
    networks:
      12306-net:

networks:
  12306-net:
